# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: circleci/mariadb:10.4
        environment:
          MYSQL_ROOT_PASSWORD: lfp
          MYSQL_DATABASE: lfp_test
          MYSQL_USER: lfp
          MYSQL_PASSWORD: lfp

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo docker-php-ext-install zip bcmath pdo_mysql

      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: yarn install

      # prepare the database
      - run: php bin/console doctrine:migration:migrate -e test

      # run tests with phpunit
      - run: ./vendor/bin/simple-phpunit
